services:
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker"
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    app:
        build: .
        ports:
            - "8000:8000"
        command: "php artisan serve --host 0.0.0.0"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        labels:
            - "traefik.http.routers.personal.rule=Host(`marqhuez.dev`)"

    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "app"
            TZ: "Europe/Budapest"
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - database_data:/var/lib/mysql:rw

volumes:
    database_data:
    vendor:
